### ISSUE TITLE
.Net Standard version

### ISSUE THREAD

**Issue by jlgrau** [slantstack/Slant.IdGen#1]
Do you have plan to provide a .net Standard version?

**Comment by jonny-novikov** [comment]
@jlgrau Yes, I plan to port all libraries in organization to .NETStandart 1.1. In next 2 weeks.
So, IdGen has no dependencies and it will be quite easy.

**Comment by thiagomajesk** [comment]
@jonny-novikov Any news on this?

**Comment by jonny-novikov** [comment]
@thiagomajesk if you are interested in Snowflake IdGen - take a look at the original fork https://github.com/RobThree/IdGen they have netstandart2 version

**Comment by RobThree** [comment]
We now have [NetStandard 1.1+ support](https://github.com/RobThree/IdGen/releases/tag/2.1).

Out of curiosity: why is this a hard fork? Besides 'rebranding', what does this version add/provide that the original doesn't / didn't? Though the license allows it, and don't _really_ mind, I'm curious to the reasoning of this.
